### ISSUE TITLE
Absoloutly not working 

### ISSUE THREAD

**Issue by Pietryszak** [luispabon/sway-ubuntu#1]
https://github.com/cyclopsian/wdisplays is not more available, so script not working 
![Zrzut ekranu 2021-04-2 o 15 50 11](https://user-images.githubusercontent.com/45850093/113421359-3b737a80-93cb-11eb-8215-d8028b4616ff.png)

Second is a few dependency problems:
![Zrzut ekranu 2021-04-2 o 15 52 52](https://user-images.githubusercontent.com/45850093/113421494-8097ac80-93cb-11eb-9319-6521df657074.png)

System Ubuntu 21.04 beta

**Comment by luispabon** [comment]
Ah I wonder what happened to wdisplays? Luckily I have a local copy with fixes required for working on newer ubuntu. I've uploaded it to my own github space and updated the Makefile.

**Comment by luispabon** [comment]
The error with libwayland 1.19 should clear itself out after first installation - we install the .debs, then we do `apt -f install` to make apt-get install the missing dependencies. Do you still get that error if you run `make libwayland-1.19`?

**Comment by Pietryszak** [comment]
> Ah I wonder what happened to wdisplays? Luckily I have a local copy with fixes required for working on newer ubuntu. I've uploaded it to my own github space and updated the Makefile.

Ok now git clone properly .

I need to use sudo apt --fix-broken install and after that make yolo
![Zrzut ekranu 2021-04-3 o 17 54 10](https://user-images.githubusercontent.com/45850093/113483839-b90bb900-94a5-11eb-8581-ac8ad4d44c56.png)
After that it's start to make files but it's another error
![Zrzut ekranu 2021-04-3 o 17 56 11](https://user-images.githubusercontent.com/45850093/113483885-e5273a00-94a5-11eb-8a08-856271096d34.png)

**Comment by luispabon** [comment]
you need to install mercurial (hg)
-- 

Kind regards,
Luis Pabon
