### ISSUE TITLE
make yolo fails while building sway

### ISSUE THREAD

**Issue by SakuAura** [luispabon/sway-ubuntu#10]
Trying this for the first time. Plain "make yolo" fails while building sway.  I am attaching the error message. 

WORKAROUND: make yolo -e SWAY_VERSION=1.6.1 WLROOT_VERSION=1.4  works, and builds sway 1.6.1

[build-error.txt](https://github.com/luispabon/sway-ubuntu/files/7605662/build-error.txt)

**Comment by SakuAura** [comment]
This is due to wlroots moving to gitlab. The fix is to change the location of wlroots repo in the makefile:

Replace    
` git clone https://github.com/swaywm/wlroots.git || echo "Already installed"`
with 
`git clone https://gitlab.freedesktop.org/wlroots/wlroots.git || echo "Already installed"`

**Comment by luispabon** [comment]
Thanks for the heads up 👍🏽
