### ISSUE TITLE
Support 22.04 LTS planned?

### ISSUE THREAD

**Issue by ngortheone** [luispabon/sway-ubuntu#13]
Is support for 22.04 LTS planned? (22.04 is around the corner)

Thanks

**Comment by luispabon** [comment]
Yes of course, although I usually switch to the next version near or just after it releases.

You can use the build system on 22.04 today though. Just make sure you don't run the makefile targets that install .deb packages. 

I pegged recently sway and wlroots to specific commits (see here https://github.com/luispabon/sway-ubuntu/blob/ea976377e001c300a4eeed547813e1591bf27317/Makefile#L11) as they recently started requiring wayland 1.20 which is not yet available to us. Once you see that update coming into your 22.04 system you should be able to build master wlroots and sway.

**Comment by luispabon** [comment]
I switched yesterday to Ubuntu 22.04 so I updated the repo for it. Closing now.
