### ISSUE TITLE
Ubuntu 22.04.1 LTS - fails because wayland-server >= 1.21 needed

### ISSUE THREAD

**Issue by arachnegl** [luispabon/sway-ubuntu#19]
I ran  `make yolo` on `Ubuntu 22.04.1 LTS` and it fails with:

`Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
`

Any advice?

**Comment by luispabon** [comment]
Are you on the [`jammy`](https://github.com/luispabon/sway-ubuntu/tree/jammy) branch?

**Comment by luispabon** [comment]
Looks like I had some changes on that branch I've never pushed, apologies.

I have set the following versions on that branch:
```
SWAY_VERSION ?= v1.7
WLROOTS_VERSION ?= 0.15
SEATD_VERSION ?= v0.6
```

Unfortunately it's not just wayland-server that needs updating, there's more including libdrm and some others that are iffy to backport from either debian or Ubuntu 22.10. You could probably push past those versions but it will be half way through the development cycles of sway 1.8 and wlroots 0.16 which I wouldn't recommend for stability reasons.

Let me know if this fixes this for you.

**Comment by arachnegl** [comment]
Many thanks for your fast reply.

It does indeed fix the issue.
