### ISSUE TITLE
make yolo errors on Ubuntu Server 22.10

### ISSUE THREAD

**Issue by humanplayer2** [luispabon/sway-ubuntu#20]
I don't know if you intend this to work on Ubuntu Server (but I hope so, it's an awesome initiative you've taken!), but in case, then `make yolo` errors (clean install with snapd removed).

Error: Symlink creation in `/usr/share/xdg-desktop-portal/portals/` errors as directory does not exist.

Fix: `mkdir -p /usr/share/xdg-desktop-portal/portals/`, then re-run `make yolo`.

Then tings continue until the dependency processing for nwg-panel, where 

    cairo\bufferproxy.c:32:10: fatal error: Python.h No such file or directory
       32 | #include <Python.h>
(I took a photo if this is too little context).

I think I'll start over and go less YOLO. Edit: I looked at the Makefile and saw that `nwg-panel-install` was second last, so I just picked up with `make swayimg-build`, which concluded.

**Comment by luispabon** [comment]
Aye you're right, my starting point has always been a regular Ubuntu Desktop installation, which already comes with those dependencies. Feel free to send in a PR with anything that might be missing in terms of header packages or whatever 👍

**Comment by stbischof** [comment]
For me it would be also good to have plain server as base

**Comment by luispabon** [comment]
Mm perhaps I can add a workflow to build `yolo` off the base `ubuntu:WHATEVER` docker image for sanity checks.

**Comment by luispabon** [comment]
If you have the time, please see if you can run yolo on your systems now from https://github.com/luispabon/sway-ubuntu/pull/21

**Comment by humanplayer2** [comment]
Exquisite! It runs to completion.

I'm flipping a bit back and forth between Ubuntu Server and Lubuntu as base for a Sway build, and there are quite a lot of things I haven't figured out with Server yet---so thank you also for the xdg-desktop-portal tip!

**Comment by humanplayer2** [comment]
PS.: This was on a fully fresh install, only changed by having `make` installed and `LD_LIBRARY_PATH` set.

**Comment by luispabon** [comment]
Great stuff, thank you @humanplayer2
