### ISSUE TITLE
wlroots build fails: `libdrm 2.4.114` needed, `2.4.113` found

### ISSUE THREAD

**Issue by humanplayer2** [luispabon/sway-ubuntu#24]
I'm running on Lubunut 22.10, and as `make yolo` reaches `wlroots`, it fails with

    Dependency libdrm found: NO found 2.4.113, but need: '>= 2.4.114'

Do you have suggestion for obtaining 2.3.114?

**Comment by luispabon** [comment]
Mm I might be able to port it from ubuntu 23.04 or debian experimental.

In the meantime, set `WLROOTS_VERSION=0.16.0` on your `.env` file, you should be able to go ahead.

**Comment by luispabon** [comment]
I've tweaked master to provide with the newest possible sway/wlroots combination until I properly look into this.

**Comment by humanplayer2** [comment]
Thank you very much, that did it!

**Comment by luispabon** [comment]
Sway 1.8 & wlroots to 0.16 are now buildable with the current setup.
