### ISSUE TITLE
REQUEST:  Can you include swaybg and swayimg in the apps

### ISSUE THREAD

**Issue by johnodon** [luispabon/sway-ubuntu#7]
https://github.com/swaywm/swaybg
https://github.com/artemsen/swayimg

**Comment by luispabon** [comment]
I can definitely look at swayimg. Swaybg has the latest version on Ubuntu's repos, you just need to `apt install swaybg` and you're good to go.

**Comment by johnodon** [comment]
> I can definitely look at swayimg. Swaybg has the latest version on Ubuntu's repos, you just need to `apt install swaybg` and you're good to go.

Perfect.  TY.

**Comment by luispabon** [comment]
Closed via 829799cffb906d4f60dba6d1b29386053984688c

Make sure you run `make install-dependencies` before running `make swayimg-build` to pick up libjpeg etc.
